services:
    application:
        build:
            context: .
            dockerfile: dockerfiles/php/Dockerfile
        image: application
        container_name: application
        tty: true
        ports:
            - "9001:9000"
        volumes:
            - .:/var/www
        networks:
            - laravel_app
        working_dir: /var/www
        depends_on:
            - db
        command: >
            sh -c "
            chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache &&
            chmod -R 775 /var/www/storage /var/www/bootstrap/cache &&
            composer install &&
            php artisan key:generate &&
            php artisan migrate --force &&
            php-fpm
            "
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "9000:80"
        volumes:
            - .:/var/www
            - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_app

    db:
        image: postgres:15
        container_name: postgres
        restart: always
        environment:
            POSTGRES_DB: task_maneger
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        ports:
            - "5433:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - laravel_app

networks:
    laravel_app:
        driver: bridge

volumes:
    pgdata:
